# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\login.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(430, 300)
        self.Login_Logo = QtWidgets.QWidget(Login)
        self.Login_Logo.setGeometry(QtCore.QRect(0, 0, 430, 150))
        self.Login_Logo.setObjectName("Login_Logo")
        self.label_3 = QtWidgets.QLabel(self.Login_Logo)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 430, 150))
        self.label_3.setStyleSheet("image:url(:/image/header.png)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.Login_Func = QtWidgets.QWidget(Login)
        self.Login_Func.setGeometry(QtCore.QRect(0, 150, 430, 150))
        self.Login_Func.setStyleSheet("image:url(:/image/blue.png)")
        self.Login_Func.setObjectName("Login_Func")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Login_Func)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(140, 20, 201, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.number = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.number.setObjectName("number")
        self.verticalLayout_4.addWidget(self.number)
        self.passwd = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd.setObjectName("passwd")
        self.verticalLayout_4.addWidget(self.passwd)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Login_Func)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 90, 201, 23))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_remenber = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_remenber.setFont(font)
        self.checkBox_remenber.setObjectName("checkBox_remenber")
        self.horizontalLayout.addWidget(self.checkBox_remenber)
        self.checkbox_autologin = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.checkbox_autologin.setFont(font)
        self.checkbox_autologin.setObjectName("checkbox_autologin")
        self.horizontalLayout.addWidget(self.checkbox_autologin)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.Login_Func)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(350, 20, 71, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bnt_regist = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.bnt_regist.setFont(font)
        self.bnt_regist.setObjectName("bnt_regist")
        self.verticalLayout_5.addWidget(self.bnt_regist)
        self.bnt_reback = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.bnt_reback.setFont(font)
        self.bnt_reback.setObjectName("bnt_reback")
        self.verticalLayout_5.addWidget(self.bnt_reback)
        self.login = QtWidgets.QPushButton(self.Login_Func)
        self.login.setGeometry(QtCore.QRect(140, 120, 200, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.label_4 = QtWidgets.QLabel(self.Login_Func)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 95, 90))
        self.label_4.setStyleSheet("image:url(:/image/header.jpg)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.checkBox_remenber.setText(_translate("Login", "记住密码"))
        self.checkbox_autologin.setText(_translate("Login", "自动登陆"))
        self.bnt_regist.setText(_translate("Login", "注册账号"))
        self.bnt_reback.setText(_translate("Login", "找回密码"))
        self.login.setText(_translate("Login", "登陆"))

import resource.login
